from __future__ import annotations

import math
import hashlib
import importlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from src.config import get_secret
from src.storage.supabase_assets import stage_timeline_assets

from .audio_mix import build_audio_mix_cmd
from .captions import write_ass_file, write_srt_file
from .timeline_schema import Timeline
from .utils import ensure_ffmpeg_exists, ensure_parent_dir, get_media_duration as _probe_media_duration, resolve_ffmpeg_exe, run_cmd


VIDEO_EXTENSIONS = {".mp4", ".mov", ".webm", ".mkv"}
_ALLOWED_XFADE_TRANSITIONS = {"fade", "fadeblack", "fadewhite", "wipeleft", "wiperight", "slideleft", "slideright", "smoothleft", "smoothright", "circleopen", "circleclose", "distance"}

# Payload keys for the four AI video clips generated by
# `src/video/ai_video_clips.py::generate_ai_video_clips`, in the same order
# they are produced there.
_AI_CLIP_PAYLOAD_KEYS = (
    "ai_opening_clip_path",
    "ai_q2_clip_path",
    "ai_q3_clip_path",
    "ai_q4_clip_path",
)

DEFAULT_PREFER_AI_ONLY_SCENE_HANDOFF = True
DEFAULT_PRESERVE_DURATION_OVER_PACING = False
AI_SCENE_DEFICIT_RECOVERY_THRESHOLD_SEC = 0.75


def compute_ai_scene_clip_mapping(num_scenes: int) -> dict[str, str]:
    """Return ``{scene_id: payload_key}`` for the four AI video clips.

    The clip generator in ``src/video/ai_video_clips.py`` places four clips at
    image indices ``0``, ``n//4``, ``n//2`` and ``3n//4`` where ``n`` is the
    scene count. This helper mirrors that formula so the render pipeline can
    attach each generated clip to the correct scene regardless of how many
    scenes the project has. The previous hardcoded ``s01/s03/s05/s07`` mapping
    only matched 8-scene projects; with the default 14-scene preset the q2/q3/q4
    clips were silently dropped and the render fell back to still images.

    When two clips land on the same scene (very small projects) the earlier
    clip in the sequence wins, so the opening clip is always preserved.
    """
    safe_scene_count = max(int(num_scenes), 1)
    targets = (
        (0, "ai_opening_clip_path"),
        (safe_scene_count // 4, "ai_q2_clip_path"),
        (safe_scene_count // 2, "ai_q3_clip_path"),
        ((3 * safe_scene_count) // 4, "ai_q4_clip_path"),
    )
    mapping: dict[str, str] = {}
    for idx, payload_key in targets:
        scene_id = f"s{idx + 1:02d}"
        mapping.setdefault(scene_id, payload_key)
    return mapping


# Retained for backwards compatibility with external imports. Represents the
# mapping for an 8-scene project; callers inside this module compute the
# mapping dynamically from the active timeline.
AI_SCENE_CLIP_MAPPING = compute_ai_scene_clip_mapping(8)


def _normalize_xfade_transition(name: str | None) -> str:
    transition = str(name or "fade").strip().lower()
    return transition if transition in _ALLOWED_XFADE_TRANSITIONS else "fade"


def _parse_resolution(resolution: str) -> tuple[int, int]:
    if "x" not in resolution:
        raise ValueError("Resolution must be formatted like 1080x1920")
    width, height = resolution.lower().split("x", maxsplit=1)
    return int(width), int(height)


def _probe_video_dimensions(video_path: Path) -> str:
    try:
        cmd = [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=width,height",
            "-of",
            "csv=s=x:p=0",
            str(video_path),
        ]
        result = subprocess.run(cmd, check=False, capture_output=True, text=True)
        dims = (result.stdout or "").strip()
        if "x" in dims:
            return dims
    except Exception:
        pass
    return "unknown"


def _apply_max_width(width: int, height: int, max_width: int) -> tuple[int, int]:
    if width <= max_width:
        return width, height
    scale = max_width / float(width)
    scaled_height = int(height * scale)
    if scaled_height % 2:
        scaled_height += 1
    return max_width, max(2, scaled_height)


def _normalize_scene_duration(duration: float, fps: int, scene_id: str) -> float:
    min_duration = 1.0 / max(1, fps)
    if not math.isfinite(duration):
        raise ValueError(f"Scene '{scene_id}' has non-finite duration {duration!r}.")
    if duration <= 0:
        raise ValueError(f"Scene '{scene_id}' has invalid duration {duration}s (must be > 0).")
    return max(duration, min_duration)


def _safe_crossfade_duration(durations: list[float], requested: float, fps: int) -> float:
    if not durations or len(durations) < 2:
        return 0.0
    if not math.isfinite(requested) or requested <= 0:
        return 0.0
    min_frame = 1.0 / max(1, fps)
    shortest_scene = min(durations)
    max_crossfade = max(0.0, shortest_scene - min_frame)
    return min(requested, max_crossfade)


def get_media_duration(path: str | Path) -> float:
    try:
        duration = float(_probe_media_duration(path))
    except Exception:
        return 0.0
    return duration if math.isfinite(duration) and duration >= 0 else 0.0


def ffprobe_duration(path: str | Path) -> float:
    return get_media_duration(path)


def get_scene_target_duration(scene_id: str, scene_duration_lookup: dict[str, float]) -> float:
    return float(scene_duration_lookup.get(scene_id, 0.0))


def get_ai_clip_for_scene(scene_id: str, ai_clip_map: dict[str, str]) -> str | None:
    clip = ai_clip_map.get(scene_id)
    return clip if clip else None


def _tmp_output_path(output_path: Path) -> Path:
    if output_path.suffix.lower() == ".mp4":
        return output_path.with_name(f"{output_path.stem}_tmp.mp4")
    return output_path.with_name(f"{output_path.stem}_tmp{output_path.suffix}")


def safe_ffmpeg_output_path(output_path: Path) -> Path:
    return output_path.with_name(f"{output_path.stem}.tmp-{os.getpid()}{output_path.suffix}")


def _assert_distinct_input_output(input_paths: list[Path], output_path: Path) -> None:
    resolved_output = output_path.resolve()
    for input_path in input_paths:
        if input_path.resolve() == resolved_output:
            raise RuntimeError("FFmpeg input and output paths must differ")


def _log_ffmpeg_io(input_paths: list[Path], tmp_output_path: Path, output_path: Path) -> None:
    print(
        "[ffmpeg_io] input=%s tmp_output=%s final_output=%s"
        % (
            [str(path) for path in input_paths],
            str(tmp_output_path),
            str(output_path),
        ),
        file=sys.stderr,
    )


def trim_clip(
    path: Path,
    duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    _assert_distinct_input_output([path], output_path)
    tmp_output_path = safe_ffmpeg_output_path(output_path)
    _log_ffmpeg_io([path], tmp_output_path, output_path)
    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(path),
        "-t",
        f"{max(0.0, duration):.6f}",
        "-an",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "24",
        "-pix_fmt",
        "yuv420p",
        str(tmp_output_path),
    ]
    ffmpeg_commands.append(cmd)
    run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_output_path, output_path)
    return output_path


def trim_clip_copy(
    path: Path,
    duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    _assert_distinct_input_output([path], output_path)
    tmp_output_path = safe_ffmpeg_output_path(output_path)
    _log_ffmpeg_io([path], tmp_output_path, output_path)
    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(path),
        "-t",
        f"{max(0.0, duration):.6f}",
        "-an",
        "-c",
        "copy",
        str(tmp_output_path),
    ]
    ffmpeg_commands.append(cmd)
    run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_output_path, output_path)
    return output_path


def concat_clips(
    paths: list[Path],
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    if not paths:
        raise ValueError("concat_clips requires at least one input path.")
    _assert_distinct_input_output(paths, output_path)
    tmp_output_path = safe_ffmpeg_output_path(output_path)
    _log_ffmpeg_io(paths, tmp_output_path, output_path)
    cmd = ["ffmpeg", "-y"]
    for clip_path in paths:
        cmd.extend(["-i", str(clip_path)])
    concat_inputs = "".join(f"[{idx}:v]" for idx in range(len(paths)))
    cmd.extend(
        [
            "-filter_complex",
            f"{concat_inputs}concat=n={len(paths)}:v=1:a=0[v]",
            "-map",
            "[v]",
            "-an",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "24",
            "-pix_fmt",
            "yuv420p",
            str(tmp_output_path),
        ]
    )
    ffmpeg_commands.append(cmd)
    run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_output_path, output_path)
    return output_path


def append_still_tail(
    ai_path: Path,
    still_path: Path,
    target_duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    ai_duration = get_media_duration(ai_path) or 0.0
    tail_duration = max(0.0, target_duration - ai_duration)
    still_tail_path = output_path.with_name(f"{output_path.stem}_still_tail.mp4")
    trim_clip(
        still_path,
        tail_duration,
        still_tail_path,
        ffmpeg_commands,
        log_path,
        command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )
    concat_clips(
        [ai_path, still_tail_path],
        output_path,
        ffmpeg_commands,
        log_path,
        command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )
    return output_path


def append_trimmed_still_tail(
    ai_path: Path,
    still_path: Path,
    target_duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    tail_start_offset_sec: float = 0.18,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    ai_duration = get_media_duration(ai_path) or 0.0
    still_duration = get_media_duration(still_path) or 0.0
    tail_duration = max(0.0, target_duration - ai_duration)
    offset = min(max(0.0, tail_start_offset_sec), max(0.0, still_duration - 0.05))
    still_tail_path = output_path.with_name(f"{output_path.stem}_still_tail_trimmed.mp4")
    _assert_distinct_input_output([still_path], still_tail_path)
    tmp_output_path = safe_ffmpeg_output_path(still_tail_path)
    _log_ffmpeg_io([still_path], tmp_output_path, still_tail_path)
    cmd = [
        "ffmpeg",
        "-y",
        "-ss",
        f"{offset:.6f}",
        "-i",
        str(still_path),
        "-t",
        f"{tail_duration:.6f}",
        "-an",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "24",
        "-pix_fmt",
        "yuv420p",
        str(tmp_output_path),
    ]
    ffmpeg_commands.append(cmd)
    run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_output_path, still_tail_path)
    concat_clips(
        [ai_path, still_tail_path],
        output_path,
        ffmpeg_commands,
        log_path,
        command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )
    return output_path


def append_freeze_tail(
    ai_path: Path,
    target_duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    ai_duration = get_media_duration(ai_path) or 0.0
    tail_duration = max(0.0, target_duration - ai_duration)
    _assert_distinct_input_output([ai_path], output_path)
    tmp_output_path = safe_ffmpeg_output_path(output_path)
    _log_ffmpeg_io([ai_path], tmp_output_path, output_path)
    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(ai_path),
        "-vf",
        f"tpad=stop_mode=clone:stop_duration={tail_duration:.6f}",
        "-an",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "24",
        "-pix_fmt",
        "yuv420p",
        str(tmp_output_path),
    ]
    ffmpeg_commands.append(cmd)
    run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_output_path, output_path)
    return output_path


def normalize_clip_to_duration(
    input_path: Path,
    target_duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    tolerance = 0.05
    actual_duration = ffprobe_duration(input_path)
    if actual_duration <= 0:
        raise RuntimeError(f"Cannot normalize clip with invalid duration: {input_path}")
    if abs(actual_duration - target_duration) <= tolerance:
        if input_path.resolve() != output_path.resolve():
            shutil.copy2(input_path, output_path)
        return output_path
    if actual_duration > target_duration:
        return trim_clip(
            input_path,
            target_duration,
            output_path,
            ffmpeg_commands,
            log_path,
            command_timeout_sec,
            workdir=workdir,
            cwd=cwd,
        )
    tail_duration = max(0.0, target_duration - actual_duration)
    if tail_duration <= 0:
        return trim_clip(
            input_path,
            target_duration,
            output_path,
            ffmpeg_commands,
            log_path,
            command_timeout_sec,
            workdir=workdir,
            cwd=cwd,
        )
    return append_still_tail(
        input_path,
        input_path,
        target_duration,
        output_path,
        ffmpeg_commands,
        log_path,
        command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )


def build_scene_final_clip(
    scene_id: str,
    still_scene_path: Path,
    ai_clip_path: Path | None,
    target_duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    prefer_ai_only_scene_handoff: bool = DEFAULT_PREFER_AI_ONLY_SCENE_HANDOFF,
    preserve_duration_over_pacing: bool = DEFAULT_PRESERVE_DURATION_OVER_PACING,
    ai_scene_deficit_recovery_threshold_sec: float = AI_SCENE_DEFICIT_RECOVERY_THRESHOLD_SEC,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> tuple[Path, str, float | None, dict[str, float | bool | str]]:
    duration_tolerance = 0.05
    if log_path:
        with log_path.open("a", encoding="utf-8") as handle:
            handle.write(f"BUILD_SCENE_FINAL_START scene_id={scene_id}\n")
    ai_duration = get_media_duration(ai_clip_path) if ai_clip_path else None
    normalization_applied = False
    if ai_clip_path is None or not ai_clip_path.exists() or ai_duration is None or ai_duration <= 0:
        final_path = trim_clip(
            still_scene_path,
            target_duration,
            output_path,
            ffmpeg_commands,
            log_path,
            command_timeout_sec,
            workdir=workdir,
            cwd=cwd,
        )
        final_duration = ffprobe_duration(final_path)
        if abs(final_duration - target_duration) > duration_tolerance:
            try:
                normalization_applied = True
                normalized_path = output_path.with_name(f"{output_path.stem}_normalized.mp4")
                final_path = normalize_clip_to_duration(
                    final_path,
                    target_duration,
                    normalized_path,
                    ffmpeg_commands,
                    log_path,
                    command_timeout_sec,
                    workdir=workdir,
                    cwd=cwd,
                )
                shutil.move(normalized_path, output_path)
                final_duration = ffprobe_duration(output_path)
                final_path = output_path
            except Exception as exc:
                raise RuntimeError(
                    f"Scene '{scene_id}' duration mismatch after still-only build: "
                    f"target={target_duration:.3f}s actual={final_duration:.3f}s delta={final_duration - target_duration:.3f}s"
                ) from exc
        if log_path:
            with log_path.open("a", encoding="utf-8") as handle:
                handle.write(
                    "BUILD_SCENE_FINAL_DONE scene_id=%s target=%.3f actual=%.3f delta=%.3f strategy=still_only\n"
                    % (scene_id, target_duration, final_duration, final_duration - target_duration)
                )
        return final_path, "still_only", ai_duration, {
            "tail_strategy": "none",
            "tail_start_offset_sec": 0.0,
            "avoided_repeated_source_image": True,
            "same_scene_tail_skipped": True,
        }

    if ai_duration >= target_duration:
        final_path = trim_clip_copy(
            ai_clip_path,
            target_duration,
            output_path,
            ffmpeg_commands,
            log_path,
            command_timeout_sec,
            workdir=workdir,
            cwd=cwd,
        )
        final_duration = ffprobe_duration(final_path)
        if abs(final_duration - target_duration) > duration_tolerance:
            try:
                normalization_applied = True
                normalized_path = output_path.with_name(f"{output_path.stem}_normalized.mp4")
                final_path = normalize_clip_to_duration(
                    final_path,
                    target_duration,
                    normalized_path,
                    ffmpeg_commands,
                    log_path,
                    command_timeout_sec,
                    workdir=workdir,
                    cwd=cwd,
                )
                shutil.move(normalized_path, output_path)
                final_duration = ffprobe_duration(output_path)
                final_path = output_path
            except Exception as exc:
                raise RuntimeError(
                    f"Scene '{scene_id}' duration mismatch after ai-only build: "
                    f"target={target_duration:.3f}s actual={final_duration:.3f}s delta={final_duration - target_duration:.3f}s"
                ) from exc
        if log_path:
            with log_path.open("a", encoding="utf-8") as handle:
                handle.write(
                    "BUILD_SCENE_FINAL_DONE scene_id=%s target=%.3f actual=%.3f delta=%.3f strategy=ai_only\n"
                    % (scene_id, target_duration, final_duration, final_duration - target_duration)
                )
        return final_path, "ai_only", ai_duration, {
            "tail_strategy": "none",
            "tail_start_offset_sec": 0.0,
            "avoided_repeated_source_image": True,
            "same_scene_tail_skipped": True,
        }

    deficit = max(0.0, target_duration - ai_duration)
    use_tail_recovery = (
        deficit > ai_scene_deficit_recovery_threshold_sec
        and preserve_duration_over_pacing
        and not prefer_ai_only_scene_handoff
    ) or (
        deficit > ai_scene_deficit_recovery_threshold_sec
        and preserve_duration_over_pacing
        and prefer_ai_only_scene_handoff
    )
    if not use_tail_recovery:
        if output_path.resolve() != ai_clip_path.resolve():
            shutil.copy2(ai_clip_path, output_path)
        final_path = output_path
        final_duration = ffprobe_duration(final_path)
        if log_path:
            with log_path.open("a", encoding="utf-8") as handle:
                handle.write(
                    "AI_SCENE_HANDOFF scene_id=%s ai_duration=%.3f target_duration=%.3f deficit=%.3f strategy_used=ai_only same_scene_tail_skipped=true\n"
                    % (scene_id, ai_duration, target_duration, deficit)
                )
                handle.write(
                    "BUILD_SCENE_FINAL_DONE scene_id=%s target=%.3f actual=%.3f delta=%.3f strategy=ai_only\n"
                    % (scene_id, target_duration, final_duration, final_duration - target_duration)
                )
        return final_path, "ai_only", ai_duration, {
            "tail_strategy": "none",
            "tail_start_offset_sec": 0.0,
            "avoided_repeated_source_image": True,
            "same_scene_tail_skipped": True,
        }

    tail_start_offset_sec = 0.18
    try:
        final_path = append_trimmed_still_tail(
            ai_clip_path,
            still_scene_path,
            target_duration,
            output_path,
            ffmpeg_commands,
            log_path,
            command_timeout_sec,
            tail_start_offset_sec=tail_start_offset_sec,
            workdir=workdir,
            cwd=cwd,
        )
        strategy_label = "ai_plus_trimmed_tail"
        tail_strategy = "trimmed_still_tail"
        avoided_repeated_source_image = True
    except Exception:
        final_path = append_freeze_tail(
            ai_clip_path,
            target_duration,
            output_path,
            ffmpeg_commands,
            log_path,
            command_timeout_sec,
            workdir=workdir,
            cwd=cwd,
        )
        strategy_label = "ai_plus_freeze_tail"
        tail_strategy = "freeze_tail"
        tail_start_offset_sec = 0.0
        avoided_repeated_source_image = True
    final_duration = ffprobe_duration(final_path)
    if abs(final_duration - target_duration) > duration_tolerance:
        try:
            normalization_applied = True
            normalized_path = output_path.with_name(f"{output_path.stem}_normalized.mp4")
            final_path = normalize_clip_to_duration(
                final_path,
                target_duration,
                normalized_path,
                ffmpeg_commands,
                log_path,
                command_timeout_sec,
                workdir=workdir,
                cwd=cwd,
            )
            shutil.move(normalized_path, output_path)
            final_duration = ffprobe_duration(output_path)
            final_path = output_path
        except Exception as exc:
            raise RuntimeError(
                f"Scene '{scene_id}' duration mismatch after ai-tail recovery build: "
                f"target={target_duration:.3f}s actual={final_duration:.3f}s delta={final_duration - target_duration:.3f}s"
            ) from exc
    if log_path:
        with log_path.open("a", encoding="utf-8") as handle:
            handle.write(
                "AI_SCENE_HANDOFF scene_id=%s ai_duration=%.3f target_duration=%.3f deficit=%.3f strategy_used=%s same_scene_tail_skipped=false\n"
                % (scene_id, ai_duration, target_duration, deficit, strategy_label)
            )
            handle.write(
                "BUILD_SCENE_FINAL_DONE scene_id=%s target=%.3f actual=%.3f delta=%.3f strategy=%s\n"
                % (scene_id, target_duration, final_duration, final_duration - target_duration, strategy_label)
            )
    return final_path, strategy_label, ai_duration, {
        "tail_strategy": tail_strategy,
        "tail_start_offset_sec": tail_start_offset_sec,
        "avoided_repeated_source_image": avoided_repeated_source_image,
        "same_scene_tail_skipped": False,
    }


def build_final_scene_clip(
    scene_id: str,
    still_scene_path: Path,
    ai_clip_path: Path | None,
    target_duration: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    prefer_ai_only_scene_handoff: bool = DEFAULT_PREFER_AI_ONLY_SCENE_HANDOFF,
    preserve_duration_over_pacing: bool = DEFAULT_PRESERVE_DURATION_OVER_PACING,
    ai_scene_deficit_recovery_threshold_sec: float = AI_SCENE_DEFICIT_RECOVERY_THRESHOLD_SEC,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> tuple[Path, str, float | None, dict[str, float | bool | str]]:
    return build_scene_final_clip(
        scene_id=scene_id,
        still_scene_path=still_scene_path,
        ai_clip_path=ai_clip_path,
        target_duration=target_duration,
        output_path=output_path,
        ffmpeg_commands=ffmpeg_commands,
        log_path=log_path,
        command_timeout_sec=command_timeout_sec,
        prefer_ai_only_scene_handoff=prefer_ai_only_scene_handoff,
        preserve_duration_over_pacing=preserve_duration_over_pacing,
        ai_scene_deficit_recovery_threshold_sec=ai_scene_deficit_recovery_threshold_sec,
        workdir=workdir,
        cwd=cwd,
    )


def concat_scene_finals(
    scene_paths: list[Path],
    stitched_path: Path,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    _concat_scenes(scene_paths, stitched_path, log_path, ffmpeg_commands, command_timeout_sec, workdir=workdir, cwd=cwd)


def add_transition_between_scene_finals(
    scene_paths: list[Path],
    stitched_path: Path,
    durations: list[float],
    fps: int,
    crossfade_duration: float,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    transition_types: list[str] | None = None,
    command_timeout_sec: float | None = None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    _crossfade_scenes(
        scene_paths=scene_paths,
        stitched_path=stitched_path,
        durations=durations,
        fps=fps,
        crossfade_duration=crossfade_duration,
        log_path=log_path,
        ffmpeg_commands=ffmpeg_commands,
        transition_types=transition_types,
        offsets=None,
        command_timeout_sec=command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )


def build_stitch_plan_from_final_clips(
    final_clip_paths: list[Path],
    transition_duration: float,
    transition_types: list[str] | None = None,
) -> dict[str, object]:
    scene_items: list[dict[str, object]] = []
    durations: list[float] = []
    offsets: list[float] = []
    cumulative = 0.0
    for idx, clip_path in enumerate(final_clip_paths):
        duration = ffprobe_duration(clip_path)
        if duration <= 0:
            raise RuntimeError(f"Invalid probed duration for final clip: {clip_path}")
        durations.append(duration)
        cumulative += duration
        offset: float | None = None
        if idx > 0 and transition_duration > 0:
            offset = max(0.0, sum(durations[:idx]) - (transition_duration * idx))
            offsets.append(offset)
        scene_items.append(
            {
                "scene_id": f"s{idx + 1:02d}",
                "final_clip_path": str(clip_path),
                "actual_duration": duration,
                "cumulative_duration": cumulative,
                "transition_offset": offset,
            }
        )
    expected_stitched_duration = float(sum(durations) - (transition_duration * max(0, len(final_clip_paths) - 1)))
    transition_by_boundary = [
        _normalize_xfade_transition(transition_types[idx] if transition_types and idx < len(transition_types) else "fade")
        for idx in range(max(0, len(final_clip_paths) - 1))
    ]
    return {
        "scene_count": len(final_clip_paths),
        "transition_duration": float(transition_duration),
        "scenes": scene_items,
        "actual_durations": durations,
        "computed_offsets": offsets,
        "transition_type_per_boundary": transition_by_boundary,
        "expected_stitched_duration": expected_stitched_duration,
        "total_transition_overlap": float(transition_duration * max(0, len(final_clip_paths) - 1)),
    }


def validate_stitch_plan(plan: dict[str, object], tolerance: float = 0.1) -> None:
    offsets = [float(v) for v in (plan.get("computed_offsets") or [])]
    durations = [float(v) for v in (plan.get("actual_durations") or [])]
    transition_duration = float(plan.get("transition_duration", 0.0) or 0.0)
    if offsets and offsets[0] < 0:
        raise RuntimeError(f"Invalid stitch plan: first offset is negative ({offsets[0]:.6f})")
    if any(offsets[idx] <= offsets[idx - 1] for idx in range(1, len(offsets))):
        raise RuntimeError(f"Invalid stitch plan: non-increasing offsets ({offsets})")
    expected_from_formula = float(sum(durations) - (transition_duration * max(0, len(durations) - 1)))
    expected_in_plan = float(plan.get("expected_stitched_duration", 0.0) or 0.0)
    if abs(expected_from_formula - expected_in_plan) > tolerance:
        raise RuntimeError(
            "Invalid stitch plan: expected duration mismatch "
            f"(formula={expected_from_formula:.6f}, plan={expected_in_plan:.6f}, tolerance={tolerance:.3f})"
        )


def stitch_with_xfade(
    plan: dict[str, object],
    output_path: Path,
    fps: int,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    command_timeout_sec: float | None = None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    scene_paths = [Path(str(item["final_clip_path"])) for item in (plan.get("scenes") or [])]
    _crossfade_scenes(
        scene_paths=scene_paths,
        stitched_path=output_path,
        durations=[float(v) for v in (plan.get("actual_durations") or [])],
        fps=fps,
        crossfade_duration=float(plan.get("transition_duration", 0.0) or 0.0),
        log_path=log_path,
        ffmpeg_commands=ffmpeg_commands,
        transition_types=[str(v) for v in (plan.get("transition_type_per_boundary") or [])],
        offsets=[float(v) for v in (plan.get("computed_offsets") or [])],
        command_timeout_sec=command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )


def stitch_with_concat_reencode(
    final_clip_paths: list[Path],
    output_path: Path,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    command_timeout_sec: float | None,
    concat_list_path: Path | None = None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    _concat_scenes(
        final_clip_paths,
        output_path,
        log_path,
        ffmpeg_commands,
        command_timeout_sec,
        concat_list_path=concat_list_path,
        workdir=workdir,
        cwd=cwd,
    )


def extend_last_scene_clip(
    last_clip_path: Path,
    deficit: float,
    output_path: Path,
    ffmpeg_commands: list[list[str]],
    log_path: Path | None,
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> Path:
    current_duration = ffprobe_duration(last_clip_path)
    if current_duration <= 0:
        raise RuntimeError(f"Cannot extend scene with invalid duration: {last_clip_path}")
    target_duration = current_duration + max(0.0, deficit)
    return normalize_clip_to_duration(
        input_path=last_clip_path,
        target_duration=target_duration,
        output_path=output_path,
        ffmpeg_commands=ffmpeg_commands,
        log_path=log_path,
        command_timeout_sec=command_timeout_sec,
        workdir=workdir,
        cwd=cwd,
    )


def validate_visual_timeline_duration(
    stitched_duration: float,
    expected_visual_duration: float,
    min_ratio: float = 0.8,
) -> tuple[bool, float]:
    if expected_visual_duration <= 0:
        return True, 1.0
    ratio = stitched_duration / expected_visual_duration if stitched_duration > 0 else 0.0
    return ratio >= min_ratio, ratio


def _zoompan_filter(scene, fps: int, width: int, height: int) -> str:
    motion = scene.motion
    if motion is None:
        return (
            f"scale={width}:{height}:force_original_aspect_ratio=increase,"
            f"crop={width}:{height},"
            "format=yuv420p"
        )

    zoom_start = motion.zoom_start if motion.type != "pan" else 1.0
    zoom_end = motion.zoom_end if motion.type != "pan" else 1.0
    x_start = motion.x_start
    x_end = motion.x_end
    y_start = motion.y if motion.type == "pan" and motion.y is not None else motion.y_start
    y_end = motion.y if motion.type == "pan" and motion.y is not None else motion.y_end

    # Render zoompan at 8× the target FPS internally so position is computed at
    # fine sub-frame resolution, then blend-downsample to the target rate with
    # minterpolate (mi_mode=blend).  Blend mode averages the 8 internal frames
    # into each output frame (temporal anti-aliasing), eliminating sub-pixel
    # timing jitter that causes visible stutter at native FPS.
    internal_fps = fps * 8
    frames = max(2, int(math.ceil(scene.duration * internal_fps)))

    # Sinusoidal ease-in/ease-out: t = (1 - cos(PI * on/frames)) / 2
    # Produces 0 at on=0 and 1 at on=frames with smooth acceleration/deceleration,
    # avoiding the abrupt mechanical starts and stops of linear interpolation.
    t_eased = f"(1-cos(PI*on/{frames}))/2"
    zoom_expr = f"{zoom_start}+({zoom_end}-{zoom_start})*{t_eased}"
    x_expr = f"({x_start}+({x_end}-{x_start})*{t_eased})*(iw-iw/zoom)"
    y_expr = f"({y_start}+({y_end}-{y_start})*{t_eased})*(ih-ih/zoom)"

    return (
        f"scale={width}:{height}:force_original_aspect_ratio=increase,"
        f"crop={width}:{height},"
        f"zoompan=z='{zoom_expr}':x='{x_expr}':y='{y_expr}':d={frames}:s={width}x{height}:fps={internal_fps},"
        f"minterpolate=fps={fps}:mi_mode=blend,"
        "format=yuv420p"
    )


def _render_scene(
    scene,
    output_path: Path,
    fps: int,
    width: int,
    height: int,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    normalized_duration = _normalize_scene_duration(float(scene.duration), fps, scene.id)
    source_path = Path(scene.image_path)
    _assert_distinct_input_output([source_path], output_path)
    tmp_scene_output = safe_ffmpeg_output_path(output_path)
    if tmp_scene_output.exists():
        tmp_scene_output.unlink()
    is_video = source_path.suffix.lower() in VIDEO_EXTENSIONS
    if is_video:
        vf_parts = [
            f"scale={width}:{height}:force_original_aspect_ratio=decrease",
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:color=black",
            f"fps={fps}",
            "setpts=PTS-STARTPTS",
        ]
        vf_parts.append("format=yuv420p")
        filter_chain = ",".join(vf_parts)
        cmd = ["ffmpeg", "-y", "-fflags", "+genpts"]
        if bool(getattr(scene, "video_loop", False)):
            cmd.extend(["-stream_loop", "-1"])
        cmd.extend([
            "-i",
            scene.image_path,
            "-t",
            f"{normalized_duration:.6f}",
            "-vf",
            filter_chain,
            "-an",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "24",
            "-pix_fmt",
            "yuv420p",
            str(tmp_scene_output),
        ])
        ffmpeg_commands.append(cmd)
        primary_result = run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, check=False, workdir=workdir, cwd=cwd)
        if not primary_result["ok"]:
            fallback_cmd = [
                "ffmpeg",
                "-y",
                "-fflags",
                "+genpts",
                "-err_detect",
                "ignore_err",
                "-i",
                scene.image_path,
                "-an",
                "-vf",
                filter_chain,
                "-t",
                f"{normalized_duration:.6f}",
                "-vsync",
                "cfr",
                "-c:v",
                "libx264",
                "-preset",
                "veryfast",
                "-crf",
                "24",
                "-pix_fmt",
                "yuv420p",
                str(tmp_scene_output),
            ]
            ffmpeg_commands.append(fallback_cmd)
            run_cmd(fallback_cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
        os.replace(tmp_scene_output, output_path)
        return

    filter_chain = _zoompan_filter(scene, fps, width, height)
    cmd = [
        "ffmpeg",
        "-y",
        "-loop",
        "1",
        "-i",
        scene.image_path,
        "-t",
        f"{normalized_duration:.6f}",
        "-vf",
        filter_chain,
        "-r",
        str(fps),
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "24",
        "-pix_fmt",
        "yuv420p",
        str(tmp_scene_output),
    ]
    ffmpeg_commands.append(cmd)
    primary_result = run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, check=False, workdir=workdir, cwd=cwd)
    if not primary_result["ok"]:
        # Fallback: simpler scale/crop without zoompan (handles unusual image formats/sizes)
        simple_filter = (
            f"scale={width}:{height}:force_original_aspect_ratio=increase,"
            f"crop={width}:{height},"
            "format=yuv420p"
        )
        fallback_cmd = [
            "ffmpeg", "-y", "-loop", "1",
            "-i", scene.image_path,
            "-t", f"{normalized_duration:.6f}",
            "-vf", simple_filter,
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "24",
            "-pix_fmt", "yuv420p",
            str(tmp_scene_output),
        ]
        ffmpeg_commands.append(fallback_cmd)
        run_cmd(fallback_cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_scene_output, output_path)


def _concat_scenes(
    scene_paths: list[Path],
    stitched_path: Path,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    command_timeout_sec: float | None,
    concat_list_path: Path | None = None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    _assert_distinct_input_output(scene_paths, stitched_path)
    concat_list = concat_list_path or stitched_path.with_suffix(".txt")
    concat_lines = [f"file '{path.as_posix()}'" for path in scene_paths]
    concat_list.write_text("\n".join(concat_lines) + "\n", encoding="utf-8")

    tmp_stitched_path = safe_ffmpeg_output_path(stitched_path)
    _log_ffmpeg_io(scene_paths, tmp_stitched_path, stitched_path)
    concat_cmd = [
        "ffmpeg",
        "-y",
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        str(concat_list),
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "24",
        "-pix_fmt",
        "yuv420p",
        str(tmp_stitched_path),
    ]
    ffmpeg_commands.append(concat_cmd)
    run_cmd(concat_cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    os.replace(tmp_stitched_path, stitched_path)


def _crossfade_scenes(
    scene_paths: list[Path],
    stitched_path: Path,
    durations: list[float],
    fps: int,
    crossfade_duration: float,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    transition_types: list[str] | None = None,
    offsets: list[float] | None = None,
    command_timeout_sec: float | None = None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> None:
    _assert_distinct_input_output(scene_paths, stitched_path)
    input_args: list[str] = []
    for path in scene_paths:
        input_args.extend(["-i", str(path)])

    filters: list[str] = []
    current_label = "[0:v]"
    for idx in range(1, len(scene_paths)):
        next_label = f"[{idx}:v]"
        output_label = f"[v{idx}]"
        transition_name = _normalize_xfade_transition(
            transition_types[idx - 1] if transition_types and idx - 1 < len(transition_types) else "fade"
        )
        offset = (
            float(offsets[idx - 1])
            if offsets is not None and idx - 1 < len(offsets)
            else max(0.0, sum(durations[:idx]) - (crossfade_duration * idx))
        )
        filters.append(
            f"{current_label}{next_label}xfade=transition={transition_name}:duration={crossfade_duration}:offset={offset}{output_label}"
        )
        current_label = output_label

    filter_complex = ";".join(filters)
    tmp_stitched_path = safe_ffmpeg_output_path(stitched_path)
    _log_ffmpeg_io(scene_paths, tmp_stitched_path, stitched_path)
    cmd = [
        "ffmpeg",
        "-y",
        *input_args,
        "-filter_complex",
        filter_complex,
        "-map",
        current_label,
        "-r",
        str(fps),
        "-vsync",
        "cfr",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "24",
        "-g",
        str(fps * 2),
        "-pix_fmt",
        "yuv420p",
        str(tmp_stitched_path),
    ]
    ffmpeg_commands.append(cmd)
    try:
        run_cmd(cmd, log_path=log_path, timeout_sec=command_timeout_sec, workdir=workdir, cwd=cwd)
    except subprocess.CalledProcessError as exc:
        _stderr = (exc.stderr or "")[-600:].strip()
        raise RuntimeError(f"xfade filter_complex failed: {_stderr}") from exc
    except Exception as exc:
        raise RuntimeError(f"xfade filter_complex failed: {exc}") from exc
    os.replace(tmp_stitched_path, stitched_path)


def _subtitle_filter(subtitle_path: Path) -> str:
    path_str = subtitle_path.as_posix()
    escaped = path_str.replace("\\", "\\\\").replace(":", "\\:")
    return f"subtitles={escaped}:charenc=UTF-8"



def _assert_filter_complex_arg(cmd: list[str]) -> None:
    if "-filter_complex" not in cmd:
        return
    idx = cmd.index("-filter_complex")
    if idx + 1 >= len(cmd):
        raise ValueError("-filter_complex must be followed by a filtergraph argument")
    filter_graph = cmd[idx + 1]
    if not isinstance(filter_graph, str) or not filter_graph.strip():
        raise ValueError(f"filtergraph argument must be a non-empty string, got {filter_graph!r}")

def _ffmpeg_version() -> str:
    try:
        from .utils import resolve_ffmpeg_exe
        ffmpeg_exe = resolve_ffmpeg_exe()
        result = subprocess.run([ffmpeg_exe, "-version"], check=False, capture_output=True, text=True)
        version_line = (result.stdout or result.stderr).splitlines()
        return version_line[0].strip() if version_line else "unknown"
    except Exception:
        return "unknown"


def _tail_log_lines(log_path: Path | None, lines: int = 50) -> list[str]:
    if not log_path or not log_path.exists():
        return []
    with log_path.open("r", encoding="utf-8", errors="ignore") as handle:
        content = handle.readlines()
    return [line.rstrip("\n") for line in content[-lines:]]


def _diagnostic_env() -> dict:
    """Gather environment info for the diagnostic report."""
    info: dict = {
        "ffmpeg_version": _ffmpeg_version(),
        "python_version": sys.version,
        "platform": platform.platform(),
    }
    try:
        total, _used, free = shutil.disk_usage("/")
        info["disk_free_gb"] = round(free / (1024 ** 3), 2)
        info["disk_total_gb"] = round(total / (1024 ** 3), 2)
    except Exception:
        pass
    return info


def _file_stat(path: str | None) -> dict:
    """Return existence and size info for a single file path."""
    if not path:
        return {"path": None, "exists": False, "size_bytes": 0}
    p = Path(path)
    try:
        stat = p.stat()
        return {"path": str(p), "exists": True, "size_bytes": stat.st_size}
    except OSError:
        return {"path": str(p), "exists": False, "size_bytes": 0}


def _scene_media_info(timeline: Timeline) -> list[dict]:
    """Return per-scene file metadata for the diagnostic report."""
    result = []
    for scene in timeline.scenes:
        info = _file_stat(scene.image_path)
        info["scene_id"] = scene.id
        info["duration"] = scene.duration
        result.append(info)
    return result


def _try_pull_project_assets_for_scene(scene_path: Path, project_root: Path, log_path: Path | None = None) -> bool:
    """Attempt to hydrate missing scene media from Supabase storage."""
    normalized_parts = scene_path.as_posix().split("/")
    try:
        data_idx = normalized_parts.index("data")
    except ValueError:
        return False
    if data_idx + 3 >= len(normalized_parts) or normalized_parts[data_idx + 1] != "projects":
        return False

    project_id = normalized_parts[data_idx + 2]
    if not project_id:
        return False

    project_dir = (project_root / "data" / "projects" / project_id).resolve()
    try:
        _sb_store = importlib.import_module("src.supabase_storage")
    except Exception:
        return False
    if not _sb_store.is_configured():
        return False

    fetched = _sb_store.pull_project_assets(project_id, project_dir)
    fetched_total = int(sum(fetched.values()))
    if log_path:
        with log_path.open("a", encoding="utf-8") as handle:
            handle.write(
                "Missing scene media detected; attempted Supabase sync for "
                f"project '{project_id}' and downloaded {fetched_total} file(s).\n"
            )
    return fetched_total > 0 and scene_path.exists()



def _scene_cache_key(scene, fps: int, width: int, height: int) -> str:
    source_path = Path(scene.image_path)
    try:
        source_stat = source_path.stat()
    except OSError:
        source_stat = None
    payload = {
        "image_path": str(source_path.resolve()),
        "video_object_path": getattr(scene, "video_object_path", None),
        "size": source_stat.st_size if source_stat else None,
        "mtime_ns": source_stat.st_mtime_ns if source_stat else None,
        "duration": scene.duration,
        "fps": fps,
        "width": width,
        "height": height,
        "motion": scene.motion.model_dump() if scene.motion else None,
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()


def _resolve_scene_clip(
    scene,
    scene_out: Path,
    fps: int,
    width: int,
    height: int,
    cache_dir: Path,
    log_path: Path | None,
    ffmpeg_commands: list[list[str]],
    command_timeout_sec: float | None,
    workdir: Path | None = None,
    cwd: Path | None = None,
) -> bool:
    # Pre-made video clips (e.g. AI-generated) — copy directly, no Ken Burns
    if str(scene.image_path).endswith(".mp4") and Path(scene.image_path).exists():
        shutil.copy2(scene.image_path, scene_out)
        return False

    cache_dir.mkdir(parents=True, exist_ok=True)
    cached_scene = cache_dir / f"{_scene_cache_key(scene, fps, width, height)}.mp4"
    if cached_scene.exists():
        shutil.copy2(cached_scene, scene_out)
        if log_path:
            with log_path.open("a", encoding="utf-8") as handle:
                handle.write(f"Using cached scene clip for {scene.id}: {cached_scene}\n")
        return True

    _render_scene(scene, scene_out, fps, width, height, log_path, ffmpeg_commands, command_timeout_sec, workdir=workdir, cwd=cwd)
    if not scene_out.exists() or scene_out.stat().st_size == 0:
        raise RuntimeError(
            f"Scene render produced no output for scene {scene.id!r}: {scene_out}"
        )
    shutil.copy2(scene_out, cached_scene)
    return False


def render_video_from_timeline(
    timeline_path: str | Path,
    out_mp4_path: str | Path,
    log_path: str | Path | None = None,
    report_path: str | Path | None = None,
    command_timeout_sec: float | None = None,
    max_width: int = 1280,
    safe_mode: bool = False,
    render_warnings: list[str] | None = None,
    force_render_rebuild: bool = False,
) -> Path:
    ensure_ffmpeg_exists()

    timeline_content = Path(timeline_path).read_text(encoding="utf-8")
    timeline_hash = hashlib.sha256(timeline_content.encode("utf-8")).hexdigest()
    timeline = Timeline.model_validate_json(timeline_content)
    if not getattr(timeline.meta, "enable_motion", True):
        for scene in timeline.scenes:
            scene.motion = None
    if not timeline.scenes:
        raise ValueError("Timeline has no scenes to render.")

    scene_mapping_warnings: list[str] = []
    for idx, scene in enumerate(timeline.scenes, start=1):
        expected_scene_id = f"s{idx:02d}"
        source_path = str(scene.image_path or "")
        if source_path and not source_path.startswith("storage://"):
            name = Path(source_path).name.lower()
            if not name.startswith(expected_scene_id):
                scene_mapping_warnings.append(
                    f"Normalized scene id {scene.id!r} -> {expected_scene_id!r} for media {scene.image_path!r}"
                )
        if scene.id != expected_scene_id:
            scene.id = expected_scene_id

    output_path = ensure_parent_dir(out_mp4_path)
    staging_root = output_path.with_name(f"{output_path.stem}_staging").resolve()
    staging_root.mkdir(parents=True, exist_ok=True)
    render_dir = output_path.with_name(f"{output_path.stem}_render_logs").resolve()
    render_dir.mkdir(parents=True, exist_ok=True)
    log_file = Path(log_path).resolve() if log_path else render_dir / "render.log"
    log_file.parent.mkdir(parents=True, exist_ok=True)
    report_file = Path(report_path).resolve() if report_path else output_path.with_name("render_report.json").resolve()
    project_root = Path.cwd().resolve()
    cache_dir = output_path.with_name("scene_cache")
    ffmpeg_commands: list[list[str]] = []
    render_error: str | None = None
    cache_hits = 0
    clean_deleted_outputs: list[str] = []
    tmp_output_path = output_path.with_name(f"{output_path.stem}_tmp{output_path.suffix}")
    if tmp_output_path.exists():
        tmp_output_path.unlink()
    if force_render_rebuild:
        candidate_paths = [output_path, tmp_output_path]
        timeline_resolved = Path(timeline_path).resolve()
        project_dir_guess = timeline_resolved.parent.parent if timeline_resolved.parent.name == "renders" else timeline_resolved.parent
        final_logs_dir = project_dir_guess / "renders" / "final_render_logs"
        candidate_paths.extend(
            [
                project_dir_guess / "renders" / "stitched.mp4",
                project_dir_guess / "renders" / "final_tmp.mp4",
                final_logs_dir / "scene_manifest.json",
            ]
        )
        for candidate in candidate_paths:
            if candidate.exists():
                candidate.unlink()
                clean_deleted_outputs.append(str(candidate))

    project_slug = (getattr(timeline.meta, "project_id", "") or "").strip() or Path(timeline_path).resolve().parent.name
    storage_buckets = {
        "images": str(get_secret("SUPABASE_IMAGES_BUCKET", "history-forge-images") or "history-forge-images"),
        "audio": str(get_secret("SUPABASE_AUDIO_BUCKET", "history-forge-audio") or "history-forge-audio"),
        "videos": str(get_secret("SUPABASE_VIDEOS_BUCKET", "generated-videos") or "generated-videos"),
    }
    timeline = stage_timeline_assets(
        timeline,
        staging_root=staging_root,
        project_slug=project_slug,
        bucket_images=storage_buckets["images"],
        bucket_audio=storage_buckets["audio"],
        bucket_videos=storage_buckets["videos"],
    )
    with log_file.open("a", encoding="utf-8") as h:
        if scene_mapping_warnings:
            h.write("=== SCENE MAPPING NORMALIZATION ===\n")
            for warning in scene_mapping_warnings:
                h.write(f"{warning}\n")
        h.write("=== STAGED SCENES ===\n")
        for s in timeline.scenes:
            h.write(f"{s.id} -> {s.image_path}\n")
    staged_files = sorted(str(path.resolve()) for path in staging_root.rglob("*") if path.is_file())

    try:
        with tempfile.TemporaryDirectory(prefix="history_forge_video_") as tmp_dir:
            tmp_path = Path(tmp_dir)
            scenes_dir = tmp_path / "scenes"
            scenes_dir.mkdir(parents=True, exist_ok=True)

            width, height = _parse_resolution(timeline.meta.resolution)
            width, height = _apply_max_width(width, height, max_width=max_width)
            fps = timeline.meta.fps

            scene_paths: list[Path] = []
            durations: list[float] = []
            scene_duration_lookup: dict[str, float] = {}
            for scene in timeline.scenes:
                scene_path = Path(scene.image_path).resolve()
                if not scene_path.exists():
                    _try_pull_project_assets_for_scene(scene_path, project_root, log_path=log_file)
                if not scene_path.exists():
                    raise FileNotFoundError(f"Scene image not found: {scene.image_path}")
                scene.image_path = str(scene_path)
                normalized_duration = _normalize_scene_duration(float(scene.duration), fps, scene.id)
                scene_out = scenes_dir / f"{scene.id}.mp4"
                if _resolve_scene_clip(scene, scene_out, fps, width, height, cache_dir, log_file, ffmpeg_commands, command_timeout_sec, workdir=render_dir, cwd=project_root):
                    cache_hits += 1
                scene_paths.append(scene_out)
                durations.append(normalized_duration)
                scene_duration_lookup[scene.id] = normalized_duration

            # ── Build one final clip per scene slot (AI replace/fill) ───────
            final_scene_dir = tmp_path / "final_scene_clips"
            final_scene_dir.mkdir(parents=True, exist_ok=True)
            manifest_items: list[dict[str, object]] = []
            final_scene_records: list[dict[str, object]] = []

            def _strip_audio(src: Path, dest: Path, target_duration: float | None = None) -> Path:
                """Re-encode AI clip to match scene format so xfade works correctly.

                Uses the same target dimensions, fps, codec, and pixel format as the
                rendered scene clips so the xfade filter never sees mismatched inputs.
                When ``target_duration`` is provided, caps the re-encoded clip with
                ``-t`` so it does not exceed the scene's target length (the xfade
                step later relies on this duration being accurate).
                Falls back to the source file if re-encoding fails.
                """
                import logging as _log_sa
                try:
                    import subprocess as _sp
                    _ffmpeg_bin = resolve_ffmpeg_exe()
                    cmd = [
                        _ffmpeg_bin, "-y", "-i", str(src),
                        "-vf", f"scale={width}:{height}:force_original_aspect_ratio=increase,crop={width}:{height},fps={fps},format=yuv420p",
                        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
                        "-an",
                    ]
                    if target_duration is not None and target_duration > 0:
                        cmd.extend(["-t", f"{target_duration:.6f}"])
                    cmd.append(str(dest))
                    _sp.run(cmd, check=True, capture_output=True)
                    if dest.exists() and dest.stat().st_size > 0:
                        return dest
                    _log_sa.getLogger(__name__).warning("ai_clip_reencode produced empty file src=%s; using original", src)
                    return src
                except Exception as _enc_err:
                    _stderr = getattr(_enc_err, "stderr", b"")
                    _stderr_str = (_stderr.decode("utf-8", errors="replace") if isinstance(_stderr, bytes) else str(_stderr))[-400:]
                    _log_sa.getLogger(__name__).warning(
                        "ai_clip_reencode_failed src=%s err=%s stderr=%s; using original (xfade may fail)",
                        src, _enc_err, _stderr_str,
                    )
                    return src

            try:
                from src.workflow.project_io import load_project_payload
                _proj_payload = load_project_payload(project_slug)
            except Exception:
                _proj_payload = {}

            _opening = str(_proj_payload.get("ai_opening_clip_path", "") or "")
            _q2 = str(_proj_payload.get("ai_q2_clip_path", "") or "")
            _q3 = str(_proj_payload.get("ai_q3_clip_path", "") or "")
            _q4 = str(_proj_payload.get("ai_q4_clip_path", "") or "")
            # Fallback: scan assets/videos/ for ai clip files if payload paths
            # are missing or stale (e.g. manual compile button before the
            # payload has been refreshed on disk).
            try:
                from src.workflow.project_io import project_dir as _proj_dir_fn
                _videos_dir = _proj_dir_fn(project_slug) / "assets" / "videos"

                def _check_disk(current_val: str, filename: str) -> str:
                    if current_val and Path(current_val).exists() and Path(current_val).stat().st_size > 0:
                        return current_val
                    candidate = _videos_dir / filename
                    if candidate.exists() and candidate.stat().st_size > 0:
                        return str(candidate)
                    return current_val

                _opening = _check_disk(_opening, "ai_opening_clip.mp4")
                _q2 = _check_disk(_q2, "ai_q2_clip.mp4")
                _q3 = _check_disk(_q3, "ai_q3_clip.mp4")
                _q4 = _check_disk(_q4, "ai_q4_clip.mp4")
            except Exception:
                pass
            # Fall back to Streamlit session state (UI path)
            try:
                import streamlit as _st_render
                _opening = _opening or str(_st_render.session_state.get("auto_ai_opening_clip") or "")
                _q2 = _q2 or str(_st_render.session_state.get("auto_ai_q2_clip") or "")
                _q3 = _q3 or str(_st_render.session_state.get("auto_ai_q3_clip") or "")
                _q4 = _q4 or str(_st_render.session_state.get("auto_ai_q4_clip") or "")
            except Exception:
                pass

            # Map each AI clip payload key to the scene it was actually
            # generated for. The clip generator picks image indices 0, n//4,
            # n//2, 3n//4 where n == number of scenes in this project; we must
            # use the same formula here so q2/q3/q4 clips land on the correct
            # scene. The old hardcoded s01/s03/s05/s07 mapping only worked for
            # 8-scene projects and silently dropped 3 out of 4 clips on the
            # default 14-scene preset.
            _ai_scene_clip_mapping = compute_ai_scene_clip_mapping(len(timeline.scenes))
            _raw_clip_sources: dict[str, str] = {
                "ai_opening_clip_path": _opening,
                "ai_q2_clip_path": _q2,
                "ai_q3_clip_path": _q3,
                "ai_q4_clip_path": _q4,
            }
            ai_clip_map_raw: dict[str, str] = {
                scene_id: _raw_clip_sources.get(payload_key, "") or ""
                for scene_id, payload_key in _ai_scene_clip_mapping.items()
            }
            ai_clip_map: dict[str, str] = {}
            for scene_id, raw_path in ai_clip_map_raw.items():
                if not raw_path:
                    continue
                src_path = Path(raw_path)
                if not src_path.exists():
                    continue
                ai_scene_path = final_scene_dir / f"{scene_id}_ai_noaudio.mp4"
                # Cap the re-encoded clip at the scene's target duration so the
                # downstream xfade step sees a clip length that matches the entry
                # we record in ``final_durations``. Without this, AI clips are
                # typically ~5s while the target scene duration may be larger,
                # causing xfade/concat mismatches.
                _scene_dur = scene_duration_lookup.get(scene_id, 0.0)
                ai_clip_map[scene_id] = str(
                    _strip_audio(
                        src_path,
                        ai_scene_path,
                        target_duration=_scene_dur if _scene_dur > 0 else None,
                    )
                )
            if log_file:
                with log_file.open("a", encoding="utf-8") as handle:
                    handle.write(
                        "ai_clip_scene_mapping scene_count=%d mapping=%s resolved=%s\n"
                        % (
                            len(timeline.scenes),
                            _ai_scene_clip_mapping,
                            {sid: Path(p).name for sid, p in ai_clip_map.items()},
                        )
                    )

            final_scene_paths: list[Path] = []
            final_durations: list[float] = []
            for index, scene in enumerate(timeline.scenes):
                scene_id = scene.id
                still_scene_path = scene_paths[index]
                target_duration = get_scene_target_duration(scene_id, scene_duration_lookup)
                ai_clip_str = get_ai_clip_for_scene(scene_id, ai_clip_map)
                ai_clip_path = Path(ai_clip_str) if ai_clip_str else None
                final_scene_path = final_scene_dir / f"{scene_id}_final.mp4"
                built_path, strategy_used, ai_duration, tail_metadata = build_scene_final_clip(
                    scene_id=scene_id,
                    still_scene_path=still_scene_path,
                    ai_clip_path=ai_clip_path,
                    target_duration=target_duration,
                    output_path=final_scene_path,
                    ffmpeg_commands=ffmpeg_commands,
                    log_path=log_file,
                    command_timeout_sec=command_timeout_sec,
                    workdir=render_dir,
                    cwd=project_root,
                )
                if not built_path.exists() or built_path.stat().st_size == 0:
                    if log_file:
                        with log_file.open("a", encoding="utf-8") as handle:
                            handle.write(
                                "final_scene_missing scene_id=%s expected=%s; rebuilding from still scene clip\n"
                                % (scene_id, final_scene_path)
                            )
                    built_path, strategy_used, ai_duration, tail_metadata = build_scene_final_clip(
                        scene_id=scene_id,
                        still_scene_path=still_scene_path,
                        ai_clip_path=None,
                        target_duration=target_duration,
                        output_path=final_scene_path,
                        ffmpeg_commands=ffmpeg_commands,
                        log_path=log_file,
                        command_timeout_sec=command_timeout_sec,
                        workdir=render_dir,
                        cwd=project_root,
                    )

                final_duration = get_media_duration(built_path)
                final_scene_paths.append(built_path)
                final_durations.append(final_duration if final_duration > 0 else target_duration)
                duration_delta = final_duration - target_duration if final_duration > 0 else 0.0
                normalization_applied = abs((final_duration if final_duration > 0 else target_duration) - target_duration) > 0.05
                scene_record = {
                    "scene_id": scene_id,
                    "target_duration": target_duration,
                    "actual_duration": final_duration,
                    "delta": duration_delta,
                    "ai_duration": ai_duration,
                    "deficit": max(0.0, target_duration - (ai_duration or 0.0)) if ai_duration is not None else 0.0,
                    "still_clip_path": str(still_scene_path),
                    "ai_clip_path": str(ai_clip_path) if ai_clip_path else "",
                    "strategy_used": strategy_used,
                    "tail_strategy": str(tail_metadata.get("tail_strategy", "none")),
                    "tail_start_offset_sec": float(tail_metadata.get("tail_start_offset_sec", 0.0) or 0.0),
                    "avoided_repeated_source_image": bool(tail_metadata.get("avoided_repeated_source_image", True)),
                    "same_scene_tail_skipped": bool(tail_metadata.get("same_scene_tail_skipped", True)),
                    "final_scene_clip_path": str(built_path),
                    "normalization_applied": normalization_applied,
                }
                final_scene_records.append(scene_record)
                manifest_items.append(scene_record)
                if log_file:
                    with log_file.open("a", encoding="utf-8") as handle:
                        handle.write(
                            "final_scene scene_id=%s still_scene_path=%s ai_clip_path=%s target_duration=%.3f ai_duration=%s strategy=%s final_scene_clip=%s final_scene_duration=%s delta=%s\n"
                            % (
                                scene_id,
                                still_scene_path,
                                str(ai_clip_path) if ai_clip_path else "",
                                target_duration,
                                f"{ai_duration:.3f}" if ai_duration is not None else "none",
                                strategy_used,
                                built_path,
                                f"{final_duration:.3f}" if final_duration is not None else "unknown",
                                f"{duration_delta:.3f}" if final_duration is not None else "unknown",
                            )
                        )

            # Validate final scene clips before stitch; rebuild missing entries from still clips.
            for idx, scene in enumerate(timeline.scenes):
                final_scene_path = final_scene_paths[idx]
                if final_scene_path.exists() and final_scene_path.stat().st_size > 0:
                    continue
                scene_id = scene.id
                still_scene_path = scene_paths[idx]
                target_duration = get_scene_target_duration(scene_id, scene_duration_lookup)
                if log_file:
                    with log_file.open("a", encoding="utf-8") as handle:
                        handle.write(
                            "final_scene_validation_error scene_id=%s missing_path=%s; rebuilding with still_only fallback\n"
                            % (scene_id, final_scene_path)
                        )
                rebuilt_path, _, _, _ = build_scene_final_clip(
                    scene_id=scene_id,
                    still_scene_path=still_scene_path,
                    ai_clip_path=None,
                    target_duration=target_duration,
                    output_path=final_scene_path,
                    ffmpeg_commands=ffmpeg_commands,
                    log_path=log_file,
                    command_timeout_sec=command_timeout_sec,
                    workdir=render_dir,
                    cwd=project_root,
                )
                final_scene_paths[idx] = rebuilt_path
                final_duration = get_media_duration(rebuilt_path)
                final_durations[idx] = final_duration if final_duration > 0 else target_duration
                final_scene_records[idx]["strategy_used"] = "still_only"
                final_scene_records[idx]["tail_strategy"] = "none"
                final_scene_records[idx]["tail_start_offset_sec"] = 0.0
                final_scene_records[idx]["avoided_repeated_source_image"] = True
                final_scene_records[idx]["same_scene_tail_skipped"] = True
                final_scene_records[idx]["final_scene_clip_path"] = str(rebuilt_path)
                final_scene_records[idx]["actual_duration"] = final_duration
                final_scene_records[idx]["delta"] = (final_duration - target_duration) if final_duration > 0 else 0.0
                final_scene_records[idx]["normalization_applied"] = abs((final_duration if final_duration > 0 else target_duration) - target_duration) > 0.05

            scene_paths = final_scene_paths
            scene_target_durations: list[float] = [get_scene_target_duration(scene.id, scene_duration_lookup) for scene in timeline.scenes]
            durations = [ffprobe_duration(path) for path in scene_paths]
            if any(duration <= 0 for duration in durations):
                raise RuntimeError(f"Failed to probe one or more final scene durations: {durations}")
            for idx, actual_duration in enumerate(durations):
                target_duration = scene_target_durations[idx]
                if abs(actual_duration - target_duration) > 0.05:
                    normalized_path = final_scene_dir / f"{timeline.scenes[idx].id}_final_normalized_exact.mp4"
                    normalize_clip_to_duration(
                        input_path=scene_paths[idx],
                        target_duration=target_duration,
                        output_path=normalized_path,
                        ffmpeg_commands=ffmpeg_commands,
                        log_path=log_file,
                        command_timeout_sec=command_timeout_sec,
                        workdir=render_dir,
                        cwd=project_root,
                    )
                    os.replace(normalized_path, scene_paths[idx])
                    durations[idx] = ffprobe_duration(scene_paths[idx])

            total_visual_expected = float(sum(scene_target_durations))
            total_visual_actual = float(sum(durations))
            voiceover_duration_for_preflight: float | None = None
            if timeline.meta.include_voiceover and timeline.meta.voiceover and timeline.meta.voiceover.path:
                voiceover_duration_for_preflight = get_media_duration(timeline.meta.voiceover.path)
            last_scene_extension_applied = 0.0
            if (
                voiceover_duration_for_preflight is not None
                and total_visual_actual < (voiceover_duration_for_preflight - 0.10)
                and scene_paths
            ):
                deficit = (voiceover_duration_for_preflight - total_visual_actual) + 0.15
                recovered_path = final_scene_dir / f"{timeline.scenes[-1].id}_final_recovered.mp4"
                extend_last_scene_clip(
                    last_clip_path=scene_paths[-1],
                    deficit=deficit,
                    output_path=recovered_path,
                    ffmpeg_commands=ffmpeg_commands,
                    log_path=log_file,
                    command_timeout_sec=command_timeout_sec,
                    workdir=render_dir,
                    cwd=project_root,
                )
                os.replace(recovered_path, scene_paths[-1])
                durations = [ffprobe_duration(path) for path in scene_paths]
                if any(duration <= 0 for duration in durations):
                    raise RuntimeError(f"Failed to re-probe final scene durations after extension: {durations}")
                total_visual_actual = float(sum(durations))
                last_scene_extension_applied = float(deficit)
            if log_file:
                with log_file.open("a", encoding="utf-8") as handle:
                    handle.write(
                        "STITCH_PREFLIGHT total_target=%.6f total_actual=%.6f voiceover=%s last_scene_extension_applied=%.6f\n"
                        % (
                            total_visual_expected,
                            total_visual_actual,
                            f"{voiceover_duration_for_preflight:.6f}" if voiceover_duration_for_preflight is not None else "none",
                            last_scene_extension_applied,
                        )
                    )

            manifest_dir = project_root / "data" / "projects" / project_slug / "renders" / "final_render_logs"
            manifest_dir.mkdir(parents=True, exist_ok=True)
            manifest_path = manifest_dir / "scene_manifest.json"
            manifest_payload = {
                "project_id": project_slug,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "scenes": manifest_items,
            }
            for idx, scene_item in enumerate(manifest_payload["scenes"]):
                if idx < len(durations):
                    scene_item["target_duration"] = float(scene_target_durations[idx])
                    scene_item["actual_duration"] = float(durations[idx])
                    scene_item["delta"] = float(durations[idx] - scene_target_durations[idx])
            manifest_path.write_text(json.dumps(manifest_payload, ensure_ascii=False, indent=2), encoding="utf-8")

            stitched_path = tmp_path / "stitched.mp4"
            stitched_list_path = manifest_dir / "stitched.txt"
            stitched_inputs_path = manifest_dir / "stitched_inputs.json"
            stitched_inputs_payload = {
                "project_id": project_slug,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "stitched_input_list": [str(path) for path in scene_paths],
            }
            stitched_inputs_path.write_text(json.dumps(stitched_inputs_payload, ensure_ascii=False, indent=2), encoding="utf-8")
            stitched_manifest: dict[str, object] = {
                "project_id": project_slug,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "ordered_scene_final_inputs": [str(path) for path in scene_paths],
                "expected_total_duration": float(total_visual_expected),
                "actual_stitched_duration": 0.0,
                "transitions_applied": False,
                "stitch_mode": "",
                "last_scene_extension_applied": float(last_scene_extension_applied),
            }
            if log_file:
                with log_file.open("a", encoding="utf-8") as handle:
                    ordered_final_inputs = [str(path) for path in scene_paths]
                    scene_strategy_map = {item.get("scene_id", ""): item.get("strategy_used", "") for item in manifest_items}
                    scene_duration_map = {
                        item.get("scene_id", ""): float(item.get("actual_duration", 0.0) or 0.0)
                        for item in manifest_items
                    }
                    handle.write(f"final_stitch ordered_final_inputs={ordered_final_inputs}\n")
                    handle.write(f"final_stitch scene_strategy_map={scene_strategy_map}\n")
                    handle.write(f"final_stitch scene_duration_map={scene_duration_map}\n")
                    handle.write(f"final_stitch force_render_rebuild={bool(force_render_rebuild)}\n")
                    handle.write(f"final_stitch deleted_or_ignored_outputs={clean_deleted_outputs}\n")
            enable_polish_transitions = bool(getattr(timeline.meta, "enable_polish_transitions", False))
            use_xfade = bool(enable_polish_transitions and (not safe_mode) and timeline.meta.crossfade and len(scene_paths) > 1)
            safe_mode_used = False
            if use_xfade:
                transition_types = getattr(timeline.meta, "transition_types", [])
                effective_crossfade = _safe_crossfade_duration(durations, float(timeline.meta.crossfade_duration), fps) if len(scene_paths) > 1 else 0.0
                stitch_plan_payload = build_stitch_plan_from_final_clips(
                    final_clip_paths=scene_paths,
                    transition_duration=effective_crossfade if effective_crossfade > 0 and len(scene_paths) > 1 else 0.0,
                    transition_types=transition_types,
                )
                stitch_plan_payload.update({
                    "project_id": project_slug,
                    "ordered_final_scene_clips": [str(p) for p in scene_paths],
                })
                validate_stitch_plan(stitch_plan_payload)
                stitch_with_xfade(
                    plan=stitch_plan_payload,
                    output_path=stitched_path,
                    fps=fps,
                    log_path=log_file,
                    ffmpeg_commands=ffmpeg_commands,
                    command_timeout_sec=command_timeout_sec,
                    workdir=render_dir,
                    cwd=project_root,
                )
                stitched_manifest["transitions_applied"] = True
                stitched_manifest["stitch_mode"] = "xfade"
            else:
                if timeline.meta.crossfade and len(scene_paths) > 1 and log_file:
                    with log_file.open("a", encoding="utf-8") as handle:
                        handle.write("Crossfade planning disabled in default workflow; using concat_reencode.\n")
                stitch_with_concat_reencode(
                    scene_paths,
                    stitched_path,
                    log_file,
                    ffmpeg_commands,
                    command_timeout_sec,
                    concat_list_path=stitched_list_path,
                    workdir=render_dir,
                    cwd=project_root,
                )
                stitched_manifest["stitch_mode"] = "concat_reencode"

            stitched_duration = ffprobe_duration(stitched_path)
            expected_stitched_duration = float(total_visual_actual)
            expected_visual_duration = float(total_visual_actual)
            timeline_ok, timeline_ratio = validate_visual_timeline_duration(stitched_duration, expected_visual_duration)
            stitched_manifest["actual_stitched_duration"] = stitched_duration

            srt_path = output_path.with_name("captions.srt")
            ass_path = output_path.with_name("captions.ass")
            subtitle_filter_applied = False
            music_mix_applied = False
            if timeline.meta.burn_captions:
                write_srt_file(srt_path, timeline)
                write_ass_file(ass_path, timeline)

            if timeline.meta.include_voiceover:
                if not timeline.meta.voiceover or not timeline.meta.voiceover.path:
                    raise FileNotFoundError("Voiceover is enabled but no voiceover path was provided.")
                voiceover_path = Path(timeline.meta.voiceover.path).resolve()
                if not voiceover_path.exists():
                    raise FileNotFoundError(f"Voiceover audio not found: {timeline.meta.voiceover.path}")
                timeline.meta.voiceover.path = str(voiceover_path)
            if timeline.meta.include_music and timeline.meta.music and timeline.meta.music.path:
                music_path = Path(timeline.meta.music.path).resolve()
                if not music_path.exists():
                    raise FileNotFoundError(f"Music file not found: {timeline.meta.music.path}")
                timeline.meta.music.path = str(music_path)

            voiceover_duration: float | None = None
            if timeline.meta.include_voiceover and timeline.meta.voiceover and timeline.meta.voiceover.path:
                voiceover_duration = get_media_duration(timeline.meta.voiceover.path)
                min_voiceover_tolerance = 0.1
                if stitched_duration + min_voiceover_tolerance < voiceover_duration:
                    scene_duration_debug = [
                        {
                            "scene_id": timeline.scenes[idx].id,
                            "target_duration": float(scene_target_durations[idx]),
                            "actual_duration": float(durations[idx]),
                            "delta": float(durations[idx] - scene_target_durations[idx]),
                            "final_scene_clip_path": str(scene_paths[idx]),
                        }
                        for idx in range(len(scene_paths))
                    ]
                    raise RuntimeError(
                        "Stitched visual duration is shorter than voiceover before final mux. "
                        f"target_total={total_visual_expected:.6f}s actual_scene_total={total_visual_actual:.6f}s "
                        f"stitched_total={stitched_duration:.6f}s voiceover_total={voiceover_duration:.6f}s "
                        f"scene_durations={scene_duration_debug}"
                    )
            if log_file:
                with log_file.open("a", encoding="utf-8") as handle:
                    handle.write(f"STITCH_MODE={stitched_manifest.get('stitch_mode', '')}\n")
                    handle.write(f"total_target_duration={total_visual_expected:.6f}\n")
                    handle.write(f"total_actual_scene_duration={total_visual_actual:.6f}\n")
                    handle.write(f"stitched_duration={stitched_duration:.6f}\n")
                    handle.write(f"voiceover_duration={(f'{voiceover_duration:.6f}' if voiceover_duration is not None else 'none')}\n")
                    handle.write(f"last_scene_extension_applied={last_scene_extension_applied:.6f}\n")
                    handle.write(f"stitched_input_list={[str(path) for path in scene_paths]}\n")

            audio_target_duration = voiceover_duration if voiceover_duration is not None else timeline.total_duration

            include_audio = timeline.meta.include_voiceover or timeline.meta.include_music
            if include_audio:
                mixed_audio_path = tmp_path / "mixed.m4a"

                def _build_mix_audio_cmd(simplify_mix: bool = False) -> list[str]:
                    audio_plan = build_audio_mix_cmd(
                        timeline.meta,
                        audio_target_duration,
                        start_index=0,
                        force_simple_vo=simplify_mix,
                        simplify_mix=simplify_mix,
                    )
                    cmd = ["ffmpeg", "-y"]
                    cmd.extend(audio_plan.input_args)
                    cmd.extend(["-filter_complex", audio_plan.filter_complex])
                    cmd.extend(audio_plan.map_args)
                    cmd.extend(["-c:a", "aac", "-b:a", "192k", "-shortest", str(mixed_audio_path)])
                    _assert_filter_complex_arg(cmd)
                    return cmd

                mix_cmd = _build_mix_audio_cmd(simplify_mix=False)
                music_mix_applied = bool(timeline.meta.include_music and timeline.meta.music and timeline.meta.music.path)
                ffmpeg_commands.append(mix_cmd)
                mix_result = run_cmd(mix_cmd, log_path=log_file, timeout_sec=command_timeout_sec, check=False, workdir=render_dir, cwd=project_root)
                if not mix_result["ok"]:
                    retry_mix_cmd = _build_mix_audio_cmd(simplify_mix=True)
                    ffmpeg_commands.append(retry_mix_cmd)
                    run_cmd(retry_mix_cmd, log_path=log_file, timeout_sec=command_timeout_sec, workdir=render_dir, cwd=project_root)

                mixed_audio_duration = ffprobe_duration(mixed_audio_path)
                final_visual_clip_count = len(scene_paths)
                if log_file:
                    with log_file.open("a", encoding="utf-8") as handle:
                        handle.write(
                            "timeline_probe stitched_duration=%.3f mixed_audio_duration=%.3f expected_total_visual_duration=%.3f final_visual_clip_count=%d ratio=%.3f\n"
                            % (
                                stitched_duration,
                                mixed_audio_duration,
                                expected_visual_duration,
                                final_visual_clip_count,
                                timeline_ratio,
                            )
                        )

                debug_mode = bool(safe_mode or os.getenv("HF_RENDER_DEBUG", "").strip().lower() in {"1", "true", "yes", "on"})
                if not timeline_ok:
                    timeline_msg = (
                        "Visual timeline too short before final mux: "
                        f"stitched={stitched_duration:.3f}s expected={expected_visual_duration:.3f}s ratio={timeline_ratio:.3f} "
                        "(minimum allowed ratio=0.800)."
                    )
                    if debug_mode and render_warnings is not None:
                        render_warnings.append(timeline_msg)
                    raise RuntimeError(timeline_msg)

                mux_cmd = ["ffmpeg", "-y", "-i", str(stitched_path), "-i", str(mixed_audio_path)]
                vf_filters: list[str] = []
                if timeline.meta.burn_captions and ass_path.exists():
                    vf_filters.append(_subtitle_filter(ass_path))
                    subtitle_filter_applied = True
                if vf_filters:
                    mux_cmd.extend(["-vf", ",".join(vf_filters)])
                mux_cmd.extend(
                    [
                        "-map",
                        "0:v:0",
                        "-map",
                        "1:a:0",
                        "-c:v",
                        "libx264",
                        "-preset",
                        "veryfast",
                        "-crf",
                        "24",
                        "-c:a",
                        "aac",
                        "-movflags",
                        "+faststart",
                    ]
                )
                mux_cmd.extend(["-shortest"])
                mux_cmd.append(str(tmp_output_path))
                ffmpeg_commands.append(mux_cmd)
                run_cmd(mux_cmd, log_path=log_file, timeout_sec=command_timeout_sec, workdir=render_dir, cwd=project_root)
            else:
                cmd = ["ffmpeg", "-y", "-i", str(stitched_path)]
                if timeline.meta.burn_captions and ass_path.exists():
                    cmd.extend(["-vf", _subtitle_filter(ass_path)])
                    subtitle_filter_applied = True
                cmd.extend(["-c:v", "libx264", "-preset", "veryfast", "-crf", "24", "-movflags", "+faststart", str(tmp_output_path)])
                ffmpeg_commands.append(cmd)
                run_cmd(cmd, log_path=log_file, timeout_sec=command_timeout_sec, workdir=render_dir, cwd=project_root)

            stitched_manifest_path = manifest_dir / "stitched_manifest.json"
            stitched_manifest_path.write_text(json.dumps(stitched_manifest, ensure_ascii=False, indent=2), encoding="utf-8")
            render_durations_path = manifest_dir / "render_durations.json"
            render_durations_payload = {
                "voiceover_duration": voiceover_duration if voiceover_duration is not None else 0.0,
                "music_duration": get_media_duration(timeline.meta.music.path) if (timeline.meta.music and timeline.meta.music.path) else 0.0,
                "stitched_duration_before_mux": stitched_duration,
                "expected_stitched_duration": expected_stitched_duration,
                "total_target_duration": total_visual_expected,
                "total_actual_scene_duration": total_visual_actual,
                "final_duration_after_mux": 0.0,
                "stitch_mode": str(stitched_manifest.get("stitch_mode", "")),
                "last_scene_extension_applied": float(stitched_manifest.get("last_scene_extension_applied", 0.0) or 0.0),
                "stitched_input_list": [str(path) for path in scene_paths],
                "safe_mode_used": bool(locals().get("safe_mode_used", False)),
            }

        if tmp_output_path.exists():
            tmp_output_path.replace(output_path)
            render_durations_payload["final_duration_after_mux"] = get_media_duration(output_path)
            render_durations_path.write_text(json.dumps(render_durations_payload, ensure_ascii=False, indent=2), encoding="utf-8")
            if log_file:
                with log_file.open("a", encoding="utf-8") as handle:
                    handle.write(
                        "FINAL_MUX_READY visual=%.3f audio=%s\n"
                        % (
                            stitched_duration,
                            f"{voiceover_duration:.3f}" if voiceover_duration is not None else "none",
                        )
                    )
            if timeline.meta.include_voiceover and timeline.meta.voiceover and timeline.meta.voiceover.path:
                expected_voiceover_duration = get_media_duration(timeline.meta.voiceover.path)
                rendered_duration = get_media_duration(output_path)
                if rendered_duration + 0.05 < expected_voiceover_duration:
                    raise RuntimeError(
                        "Rendered video is shorter than the voiceover "
                        f"({rendered_duration:.3f}s < {expected_voiceover_duration:.3f}s)."
                    )
        else:
            raise RuntimeError(f"Expected render output was not created: {tmp_output_path}")
    except Exception as exc:
        render_error = str(exc)
        raise
    finally:
        try:
            meta = timeline.meta
            report = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "status": "failure" if render_error else "success",
                "success": render_error is None,
                "error_excerpt": render_error,
                "timeline_hash": timeline_hash,
                "command_timeout_sec": command_timeout_sec,
                "environment": _diagnostic_env(),
                "input_media": _scene_media_info(timeline),
                "audio": {
                    "voiceover": _file_stat(meta.voiceover.path if meta.voiceover else None),
                    "music": _file_stat(meta.music.path if meta.music else None),
                },
                "requested_aspect_ratio": meta.aspect_ratio,
                "resolved_output_size": meta.resolution,
                "subtitles_enabled": bool(meta.burn_captions),
                "subtitle_filter_applied": bool(locals().get("subtitle_filter_applied", False)),
                "effect_style": str(getattr(meta, "video_effects_style", "Ken Burns - Standard")),
                "music_enabled": bool(meta.include_music),
                "music_track": str(meta.music.path if meta.music and meta.music.path else ""),
                "music_mix_applied": bool(locals().get("music_mix_applied", False)),
                "output_path": str(output_path),
                "actual_output_size": _probe_video_dimensions(output_path) if output_path.exists() else "unknown",
                "scene_cache": {
                    "directory": str(cache_dir),
                    "hits": cache_hits,
                    "total_scenes": len(timeline.scenes),
                },
                "force_render_rebuild": bool(force_render_rebuild),
                "clean_deleted_outputs": clean_deleted_outputs,
                "ffmpeg_commands": [" ".join(cmd) for cmd in ffmpeg_commands],
                "tmp_output_path": str(tmp_output_path),
                "log_file": str(log_file),
                "render_dir": str(render_dir),
                "report_file": str(report_file),
                "staging": {
                    "staging_root": str(staging_root),
                    "file_count": len(staged_files),
                    "files": staged_files,
                    "buckets": storage_buckets,
                    "mapping_strategy": {
                        "local_prefix_images": os.getenv("LOCAL_PREFIX_IMAGES", "data/projects/{project}/assets/images/"),
                        "local_prefix_audio": os.getenv("LOCAL_PREFIX_AUDIO", "data/projects/{project}/assets/audio/"),
                        "storage_prefix_images": os.getenv("STORAGE_PREFIX_IMAGES", "{project}/"),
                        "storage_prefix_audio": os.getenv("STORAGE_PREFIX_AUDIO", "{project}/"),
                    },
                },
                "log_tail": _tail_log_lines(log_file, lines=50),
            }
            report_file.parent.mkdir(parents=True, exist_ok=True)
            report_file.write_text(json.dumps(report, indent=2), encoding="utf-8")
        except Exception:
            # Never let report writing mask the original render exception
            pass

    return output_path
